/* soapCalculatorSoapProxy.h
   Generated by gSOAP 2.8.97 for calculator.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapCalculatorSoapProxy_H
#define soapCalculatorSoapProxy_H
#include "soapH.h"

    class SOAP_CMAC CalculatorSoapProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'CalculatorSoapProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in calculator.h, if any
        /// Construct a proxy with new managing context
        CalculatorSoapProxy();
        /// Copy constructor
        CalculatorSoapProxy(const CalculatorSoapProxy& rhs);
        /// Construct proxy given a shared managing context
        CalculatorSoapProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        CalculatorSoapProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        CalculatorSoapProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        CalculatorSoapProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        CalculatorSoapProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        CalculatorSoapProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~CalculatorSoapProxy();
        /// Initializer used by constructors
        virtual void CalculatorSoapProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual CalculatorSoapProxy *copy();
        /// Copy assignment
        CalculatorSoapProxy& operator=(const CalculatorSoapProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'Add' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int Add(_tempuri__Add *tempuri__Add, _tempuri__AddResponse &tempuri__AddResponse) { return this->Add(NULL, NULL, tempuri__Add, tempuri__AddResponse); }
        /// Web service synchronous operation 'Add' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int Add(const char *soap_endpoint_url, const char *soap_action, _tempuri__Add *tempuri__Add, _tempuri__AddResponse &tempuri__AddResponse) { return this->send_Add(soap_endpoint_url, soap_action, tempuri__Add) || this->recv_Add(tempuri__AddResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_Add' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_Add(const char *soap_endpoint_url, const char *soap_action, _tempuri__Add *tempuri__Add);
        /// Web service asynchronous operation 'recv_Add' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_Add(_tempuri__AddResponse &tempuri__AddResponse);
        //
        /// Web service synchronous operation 'Subtract' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int Subtract(_tempuri__Subtract *tempuri__Subtract, _tempuri__SubtractResponse &tempuri__SubtractResponse) { return this->Subtract(NULL, NULL, tempuri__Subtract, tempuri__SubtractResponse); }
        /// Web service synchronous operation 'Subtract' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int Subtract(const char *soap_endpoint_url, const char *soap_action, _tempuri__Subtract *tempuri__Subtract, _tempuri__SubtractResponse &tempuri__SubtractResponse) { return this->send_Subtract(soap_endpoint_url, soap_action, tempuri__Subtract) || this->recv_Subtract(tempuri__SubtractResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_Subtract' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_Subtract(const char *soap_endpoint_url, const char *soap_action, _tempuri__Subtract *tempuri__Subtract);
        /// Web service asynchronous operation 'recv_Subtract' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_Subtract(_tempuri__SubtractResponse &tempuri__SubtractResponse);
        //
        /// Web service synchronous operation 'Multiply' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int Multiply(_tempuri__Multiply *tempuri__Multiply, _tempuri__MultiplyResponse &tempuri__MultiplyResponse) { return this->Multiply(NULL, NULL, tempuri__Multiply, tempuri__MultiplyResponse); }
        /// Web service synchronous operation 'Multiply' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int Multiply(const char *soap_endpoint_url, const char *soap_action, _tempuri__Multiply *tempuri__Multiply, _tempuri__MultiplyResponse &tempuri__MultiplyResponse) { return this->send_Multiply(soap_endpoint_url, soap_action, tempuri__Multiply) || this->recv_Multiply(tempuri__MultiplyResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_Multiply' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_Multiply(const char *soap_endpoint_url, const char *soap_action, _tempuri__Multiply *tempuri__Multiply);
        /// Web service asynchronous operation 'recv_Multiply' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_Multiply(_tempuri__MultiplyResponse &tempuri__MultiplyResponse);
        //
        /// Web service synchronous operation 'Divide' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int Divide(_tempuri__Divide *tempuri__Divide, _tempuri__DivideResponse &tempuri__DivideResponse) { return this->Divide(NULL, NULL, tempuri__Divide, tempuri__DivideResponse); }
        /// Web service synchronous operation 'Divide' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int Divide(const char *soap_endpoint_url, const char *soap_action, _tempuri__Divide *tempuri__Divide, _tempuri__DivideResponse &tempuri__DivideResponse) { return this->send_Divide(soap_endpoint_url, soap_action, tempuri__Divide) || this->recv_Divide(tempuri__DivideResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_Divide' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_Divide(const char *soap_endpoint_url, const char *soap_action, _tempuri__Divide *tempuri__Divide);
        /// Web service asynchronous operation 'recv_Divide' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_Divide(_tempuri__DivideResponse &tempuri__DivideResponse);
        //
        /// Web service synchronous operation 'Add' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int Add_(_tempuri__Add *tempuri__Add, _tempuri__AddResponse &tempuri__AddResponse) { return this->Add_(NULL, NULL, tempuri__Add, tempuri__AddResponse); }
        /// Web service synchronous operation 'Add' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int Add_(const char *soap_endpoint_url, const char *soap_action, _tempuri__Add *tempuri__Add, _tempuri__AddResponse &tempuri__AddResponse) { return this->send_Add_(soap_endpoint_url, soap_action, tempuri__Add) || this->recv_Add_(tempuri__AddResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_Add' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_Add_(const char *soap_endpoint_url, const char *soap_action, _tempuri__Add *tempuri__Add);
        /// Web service asynchronous operation 'recv_Add' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_Add_(_tempuri__AddResponse &tempuri__AddResponse);
        //
        /// Web service synchronous operation 'Subtract' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int Subtract_(_tempuri__Subtract *tempuri__Subtract, _tempuri__SubtractResponse &tempuri__SubtractResponse) { return this->Subtract_(NULL, NULL, tempuri__Subtract, tempuri__SubtractResponse); }
        /// Web service synchronous operation 'Subtract' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int Subtract_(const char *soap_endpoint_url, const char *soap_action, _tempuri__Subtract *tempuri__Subtract, _tempuri__SubtractResponse &tempuri__SubtractResponse) { return this->send_Subtract_(soap_endpoint_url, soap_action, tempuri__Subtract) || this->recv_Subtract_(tempuri__SubtractResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_Subtract' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_Subtract_(const char *soap_endpoint_url, const char *soap_action, _tempuri__Subtract *tempuri__Subtract);
        /// Web service asynchronous operation 'recv_Subtract' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_Subtract_(_tempuri__SubtractResponse &tempuri__SubtractResponse);
        //
        /// Web service synchronous operation 'Multiply' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int Multiply_(_tempuri__Multiply *tempuri__Multiply, _tempuri__MultiplyResponse &tempuri__MultiplyResponse) { return this->Multiply_(NULL, NULL, tempuri__Multiply, tempuri__MultiplyResponse); }
        /// Web service synchronous operation 'Multiply' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int Multiply_(const char *soap_endpoint_url, const char *soap_action, _tempuri__Multiply *tempuri__Multiply, _tempuri__MultiplyResponse &tempuri__MultiplyResponse) { return this->send_Multiply_(soap_endpoint_url, soap_action, tempuri__Multiply) || this->recv_Multiply_(tempuri__MultiplyResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_Multiply' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_Multiply_(const char *soap_endpoint_url, const char *soap_action, _tempuri__Multiply *tempuri__Multiply);
        /// Web service asynchronous operation 'recv_Multiply' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_Multiply_(_tempuri__MultiplyResponse &tempuri__MultiplyResponse);
        //
        /// Web service synchronous operation 'Divide' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int Divide_(_tempuri__Divide *tempuri__Divide, _tempuri__DivideResponse &tempuri__DivideResponse) { return this->Divide_(NULL, NULL, tempuri__Divide, tempuri__DivideResponse); }
        /// Web service synchronous operation 'Divide' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int Divide_(const char *soap_endpoint_url, const char *soap_action, _tempuri__Divide *tempuri__Divide, _tempuri__DivideResponse &tempuri__DivideResponse) { return this->send_Divide_(soap_endpoint_url, soap_action, tempuri__Divide) || this->recv_Divide_(tempuri__DivideResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_Divide' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_Divide_(const char *soap_endpoint_url, const char *soap_action, _tempuri__Divide *tempuri__Divide);
        /// Web service asynchronous operation 'recv_Divide' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_Divide_(_tempuri__DivideResponse &tempuri__DivideResponse);
    };
#endif
